import type { GameDayPromotionDefinition } from "@/domain/entities/game-day-promotion";

/**
 * Static fictional promotion catalog.
 * demandBoost values calibrated against empirical demand scores (~36–72):
 * +4 ≈ +720 att, +6 ≈ +1,080, +8 ≈ +1,440, +10 ≈ +1,800 at 18k / $45.
 */

export const GAME_DAY_PROMOTION_CATALOG: readonly GameDayPromotionDefinition[] = [
  // ── Theme nights ──────────────────────────────────────────────
  {
    id: "opening_night",
    name: "Opening Night",
    description: "Celebrate the first home tip-off of the season with fan festivities.",
    category: "theme_night",
    objective: "fan_engagement",
    targetAudience: "general",
    cost: 35_000,
    leadTimeDays: 5,
    effects: {
      demandBoost: 6,
      merchMultiplier: 1.15,
      concessionMultiplier: 1.08,
      awarenessBump: 2,
      sentimentBump: 3,
      reputationBump: 1,
      mediaBump: 2,
    },
    maxUsesPerSeason: 1,
    cooldownDays: 365,
    requirements: { openingNightOnly: true },
  },
  {
    id: "rivalry_night",
    name: "Rivalry Night",
    description: "A charged atmosphere for a divisional home matchup.",
    category: "theme_night",
    objective: "attendance",
    targetAudience: "general",
    cost: 28_000,
    leadTimeDays: 5,
    effects: {
      demandBoost: 7,
      merchMultiplier: 1.12,
      concessionMultiplier: 1.1,
      awarenessBump: 1,
      sentimentBump: 2,
      reputationBump: 0,
      mediaBump: 2,
    },
    maxUsesPerSeason: 3,
    cooldownDays: 21,
    requirements: { divisionMatchupOnly: true },
  },
  {
    id: "kids_night",
    name: "Kids Night",
    description: "Family-friendly activities and kid-focused entertainment.",
    category: "theme_night",
    objective: "attendance",
    targetAudience: "youth",
    cost: 18_000,
    leadTimeDays: 4,
    effects: {
      demandBoost: 4,
      merchMultiplier: 1.05,
      concessionMultiplier: 1.12,
      awarenessBump: 1,
      sentimentBump: 2,
      reputationBump: 1,
      mediaBump: 1,
    },
    maxUsesPerSeason: 4,
    cooldownDays: 14,
  },
  {
    id: "family_night",
    name: "Family Night",
    description: "A welcoming night for families with special programming.",
    category: "theme_night",
    objective: "attendance",
    targetAudience: "families",
    cost: 20_000,
    leadTimeDays: 4,
    effects: {
      demandBoost: 4,
      merchMultiplier: 1.06,
      concessionMultiplier: 1.14,
      awarenessBump: 1,
      sentimentBump: 2,
      reputationBump: 1,
      mediaBump: 1,
    },
    maxUsesPerSeason: 5,
    cooldownDays: 14,
  },
  {
    id: "community_night",
    name: "Community Night",
    description: "Celebrate the local community with neighborhood partners.",
    category: "theme_night",
    objective: "community",
    targetAudience: "community",
    cost: 16_000,
    leadTimeDays: 5,
    effects: {
      demandBoost: 3,
      merchMultiplier: 1.04,
      concessionMultiplier: 1.05,
      awarenessBump: 2,
      sentimentBump: 3,
      reputationBump: 2,
      mediaBump: 1,
    },
    maxUsesPerSeason: 4,
    cooldownDays: 14,
  },
  {
    id: "fan_appreciation_night",
    name: "Fan Appreciation Night",
    description: "Thank the fans with special in-arena recognition.",
    category: "theme_night",
    objective: "fan_engagement",
    targetAudience: "general",
    cost: 22_000,
    leadTimeDays: 5,
    effects: {
      demandBoost: 4,
      merchMultiplier: 1.08,
      concessionMultiplier: 1.06,
      awarenessBump: 1,
      sentimentBump: 4,
      reputationBump: 1,
      mediaBump: 1,
    },
    maxUsesPerSeason: 2,
    cooldownDays: 30,
  },
  {
    id: "retro_night",
    name: "Retro Night",
    description: "Throwback jerseys, classic music, and vintage arena vibes.",
    category: "theme_night",
    objective: "balanced",
    targetAudience: "general",
    cost: 24_000,
    leadTimeDays: 7,
    effects: {
      demandBoost: 5,
      merchMultiplier: 1.18,
      concessionMultiplier: 1.05,
      awarenessBump: 2,
      sentimentBump: 2,
      reputationBump: 1,
      mediaBump: 2,
    },
    maxUsesPerSeason: 2,
    cooldownDays: 28,
  },
  {
    id: "college_night",
    name: "College Night",
    description: "Special pricing and programming for college students.",
    category: "theme_night",
    objective: "attendance",
    targetAudience: "students",
    cost: 15_000,
    leadTimeDays: 5,
    effects: {
      demandBoost: 4,
      merchMultiplier: 1.04,
      concessionMultiplier: 1.08,
      awarenessBump: 1,
      sentimentBump: 1,
      reputationBump: 0,
      mediaBump: 1,
    },
    maxUsesPerSeason: 4,
    cooldownDays: 14,
  },
  {
    id: "youth_basketball_night",
    name: "Youth Basketball Night",
    description: "Local youth teams take the floor for pregame clinics.",
    category: "theme_night",
    objective: "community",
    targetAudience: "youth",
    cost: 17_000,
    leadTimeDays: 6,
    effects: {
      demandBoost: 3,
      merchMultiplier: 1.05,
      concessionMultiplier: 1.07,
      awarenessBump: 1,
      sentimentBump: 2,
      reputationBump: 2,
      mediaBump: 1,
    },
    maxUsesPerSeason: 3,
    cooldownDays: 21,
  },
  {
    id: "season_celebration",
    name: "Season Celebration",
    description: "A mid- or late-season celebration of the franchise year.",
    category: "theme_night",
    objective: "fan_engagement",
    targetAudience: "general",
    cost: 30_000,
    leadTimeDays: 7,
    effects: {
      demandBoost: 5,
      merchMultiplier: 1.1,
      concessionMultiplier: 1.08,
      awarenessBump: 2,
      sentimentBump: 3,
      reputationBump: 1,
      mediaBump: 2,
    },
    maxUsesPerSeason: 1,
    cooldownDays: 60,
  },

  // ── Giveaways ─────────────────────────────────────────────────
  {
    id: "bobblehead_giveaway",
    name: "Bobblehead Giveaway",
    description: "Limited bobbleheads for early-arriving fans.",
    category: "giveaway",
    objective: "attendance",
    targetAudience: "general",
    cost: 65_000,
    leadTimeDays: 21,
    quantityAvailable: 12_000,
    effects: {
      demandBoost: 8,
      merchMultiplier: 1.1,
      concessionMultiplier: 1.06,
      awarenessBump: 2,
      sentimentBump: 3,
      reputationBump: 1,
      mediaBump: 2,
    },
    maxUsesPerSeason: 2,
    cooldownDays: 28,
  },
  {
    id: "team_poster_giveaway",
    name: "Team Poster Giveaway",
    description: "Collectible team posters for fans at the gate.",
    category: "giveaway",
    objective: "attendance",
    targetAudience: "general",
    cost: 28_000,
    leadTimeDays: 14,
    quantityAvailable: 15_000,
    effects: {
      demandBoost: 4,
      merchMultiplier: 1.04,
      concessionMultiplier: 1.03,
      awarenessBump: 1,
      sentimentBump: 1,
      reputationBump: 0,
      mediaBump: 1,
    },
    maxUsesPerSeason: 4,
    cooldownDays: 14,
  },
  {
    id: "tshirt_giveaway",
    name: "T-Shirt Giveaway",
    description: "Team t-shirts distributed to the first fans through the doors.",
    category: "giveaway",
    objective: "attendance",
    targetAudience: "general",
    cost: 45_000,
    leadTimeDays: 18,
    quantityAvailable: 12_000,
    effects: {
      demandBoost: 6,
      merchMultiplier: 0.95,
      concessionMultiplier: 1.05,
      awarenessBump: 1,
      sentimentBump: 2,
      reputationBump: 0,
      mediaBump: 1,
    },
    maxUsesPerSeason: 3,
    cooldownDays: 21,
  },
  {
    id: "hat_giveaway",
    name: "Hat Giveaway",
    description: "Branded hats for fans who arrive early.",
    category: "giveaway",
    objective: "attendance",
    targetAudience: "general",
    cost: 40_000,
    leadTimeDays: 16,
    quantityAvailable: 10_000,
    effects: {
      demandBoost: 5,
      merchMultiplier: 0.97,
      concessionMultiplier: 1.04,
      awarenessBump: 1,
      sentimentBump: 2,
      reputationBump: 0,
      mediaBump: 1,
    },
    maxUsesPerSeason: 3,
    cooldownDays: 21,
  },
  {
    id: "jersey_giveaway",
    name: "Jersey Giveaway",
    description: "Replica jerseys for a limited number of early-arriving fans.",
    category: "giveaway",
    objective: "attendance",
    targetAudience: "general",
    cost: 95_000,
    leadTimeDays: 28,
    quantityAvailable: 8_000,
    effects: {
      demandBoost: 10,
      merchMultiplier: 0.92,
      concessionMultiplier: 1.08,
      awarenessBump: 3,
      sentimentBump: 4,
      reputationBump: 1,
      mediaBump: 3,
    },
    maxUsesPerSeason: 1,
    cooldownDays: 45,
  },
  {
    id: "rally_towel_giveaway",
    name: "Rally Towel Giveaway",
    description: "Rally towels for a loud home crowd.",
    category: "giveaway",
    objective: "fan_engagement",
    targetAudience: "general",
    cost: 22_000,
    leadTimeDays: 14,
    quantityAvailable: 15_000,
    effects: {
      demandBoost: 4,
      merchMultiplier: 1.03,
      concessionMultiplier: 1.04,
      awarenessBump: 1,
      sentimentBump: 2,
      reputationBump: 0,
      mediaBump: 1,
    },
    maxUsesPerSeason: 4,
    cooldownDays: 14,
  },

  // ── Ticket promotions ─────────────────────────────────────────
  {
    id: "discount_night",
    name: "Discount Night",
    description: "Reduced ticket prices to boost walk-up and group sales.",
    category: "ticket_promotion",
    objective: "attendance",
    targetAudience: "general",
    cost: 12_000,
    leadTimeDays: 10,
    effects: {
      demandBoost: 3,
      merchMultiplier: 1.02,
      concessionMultiplier: 1.06,
      ticketPriceMultiplier: 0.8,
      awarenessBump: 0,
      sentimentBump: 1,
      reputationBump: 0,
      mediaBump: 0,
    },
    maxUsesPerSeason: 5,
    cooldownDays: 14,
  },
  {
    id: "family_ticket_promotion",
    name: "Family Ticket Promotion",
    description: "Discounted family ticket packages.",
    category: "ticket_promotion",
    objective: "attendance",
    targetAudience: "families",
    cost: 15_000,
    leadTimeDays: 10,
    effects: {
      demandBoost: 4,
      merchMultiplier: 1.05,
      concessionMultiplier: 1.12,
      ticketPriceMultiplier: 0.85,
      awarenessBump: 1,
      sentimentBump: 2,
      reputationBump: 0,
      mediaBump: 0,
    },
    maxUsesPerSeason: 4,
    cooldownDays: 14,
  },
  {
    id: "student_ticket_promotion",
    name: "Student Ticket Promotion",
    description: "Special student pricing for a packed student section.",
    category: "ticket_promotion",
    objective: "attendance",
    targetAudience: "students",
    cost: 10_000,
    leadTimeDays: 8,
    effects: {
      demandBoost: 3,
      merchMultiplier: 1.02,
      concessionMultiplier: 1.08,
      ticketPriceMultiplier: 0.75,
      awarenessBump: 1,
      sentimentBump: 1,
      reputationBump: 0,
      mediaBump: 0,
    },
    maxUsesPerSeason: 5,
    cooldownDays: 12,
  },
  {
    id: "kids_ticket_promotion",
    name: "Kids Ticket Promotion",
    description: "Reduced kids tickets to encourage family attendance.",
    category: "ticket_promotion",
    objective: "attendance",
    targetAudience: "youth",
    cost: 10_000,
    leadTimeDays: 8,
    effects: {
      demandBoost: 3,
      merchMultiplier: 1.04,
      concessionMultiplier: 1.1,
      ticketPriceMultiplier: 0.82,
      awarenessBump: 0,
      sentimentBump: 1,
      reputationBump: 0,
      mediaBump: 0,
    },
    maxUsesPerSeason: 5,
    cooldownDays: 12,
  },

  // ── Entertainment ─────────────────────────────────────────────
  {
    id: "halftime_entertainment",
    name: "Halftime Entertainment",
    description: "A special halftime show for the home crowd.",
    category: "entertainment",
    objective: "fan_engagement",
    targetAudience: "general",
    cost: 55_000,
    leadTimeDays: 21,
    effects: {
      demandBoost: 5,
      merchMultiplier: 1.05,
      concessionMultiplier: 1.08,
      awarenessBump: 2,
      sentimentBump: 2,
      reputationBump: 1,
      mediaBump: 2,
    },
    maxUsesPerSeason: 3,
    cooldownDays: 21,
  },
  {
    id: "mascot_event",
    name: "Mascot Event",
    description: "Extended mascot appearances and kid meet-ups.",
    category: "entertainment",
    objective: "fan_engagement",
    targetAudience: "families",
    cost: 25_000,
    leadTimeDays: 14,
    effects: {
      demandBoost: 3,
      merchMultiplier: 1.06,
      concessionMultiplier: 1.07,
      awarenessBump: 1,
      sentimentBump: 2,
      reputationBump: 0,
      mediaBump: 1,
    },
    maxUsesPerSeason: 4,
    cooldownDays: 14,
  },
  {
    id: "fan_meet_and_greet",
    name: "Fan Meet & Greet",
    description: "Postgame fan meet-and-greet with selected players.",
    category: "entertainment",
    objective: "fan_engagement",
    targetAudience: "general",
    cost: 40_000,
    leadTimeDays: 21,
    effects: {
      demandBoost: 5,
      merchMultiplier: 1.12,
      concessionMultiplier: 1.04,
      awarenessBump: 2,
      sentimentBump: 4,
      reputationBump: 1,
      mediaBump: 2,
    },
    maxUsesPerSeason: 2,
    cooldownDays: 28,
  },
  {
    id: "youth_clinic",
    name: "Youth Clinic",
    description: "A youth basketball clinic before tip-off.",
    category: "entertainment",
    objective: "community",
    targetAudience: "youth",
    cost: 30_000,
    leadTimeDays: 21,
    effects: {
      demandBoost: 4,
      merchMultiplier: 1.05,
      concessionMultiplier: 1.06,
      awarenessBump: 1,
      sentimentBump: 2,
      reputationBump: 2,
      mediaBump: 1,
    },
    maxUsesPerSeason: 3,
    cooldownDays: 21,
  },
  {
    id: "postgame_fireworks",
    name: "Postgame Fireworks",
    description: "A postgame fireworks show for the home crowd.",
    category: "entertainment",
    objective: "attendance",
    targetAudience: "families",
    cost: 80_000,
    leadTimeDays: 28,
    effects: {
      demandBoost: 9,
      merchMultiplier: 1.08,
      concessionMultiplier: 1.1,
      awarenessBump: 3,
      sentimentBump: 3,
      reputationBump: 1,
      mediaBump: 3,
    },
    maxUsesPerSeason: 2,
    cooldownDays: 30,
  },
  {
    id: "special_guest_appearance",
    name: "Special Guest Appearance",
    description: "A special fictional guest appearance for entertainment value.",
    category: "entertainment",
    objective: "awareness",
    targetAudience: "general",
    cost: 120_000,
    leadTimeDays: 35,
    effects: {
      demandBoost: 11,
      merchMultiplier: 1.15,
      concessionMultiplier: 1.08,
      awarenessBump: 4,
      sentimentBump: 3,
      reputationBump: 2,
      mediaBump: 4,
    },
    maxUsesPerSeason: 1,
    cooldownDays: 60,
  },

  // ── Community / PR ────────────────────────────────────────────
  {
    id: "charity_night",
    name: "Charity Night",
    description: "Proceeds and awareness for a local fictional charity partner.",
    category: "community_pr",
    objective: "community",
    targetAudience: "community",
    cost: 20_000,
    leadTimeDays: 7,
    effects: {
      demandBoost: 2,
      merchMultiplier: 1.03,
      concessionMultiplier: 1.02,
      awarenessBump: 2,
      sentimentBump: 3,
      reputationBump: 3,
      mediaBump: 2,
    },
    maxUsesPerSeason: 3,
    cooldownDays: 21,
  },
  {
    id: "local_community_night",
    name: "Local Community Night",
    description: "Spotlight local organizations and neighborhood groups.",
    category: "community_pr",
    objective: "community",
    targetAudience: "community",
    cost: 14_000,
    leadTimeDays: 6,
    effects: {
      demandBoost: 2,
      merchMultiplier: 1.02,
      concessionMultiplier: 1.03,
      awarenessBump: 2,
      sentimentBump: 3,
      reputationBump: 2,
      mediaBump: 1,
    },
    maxUsesPerSeason: 4,
    cooldownDays: 14,
  },
  {
    id: "local_heroes_night",
    name: "Local Heroes Night",
    description: "Honor local first responders and community heroes.",
    category: "community_pr",
    objective: "community",
    targetAudience: "community",
    cost: 18_000,
    leadTimeDays: 8,
    effects: {
      demandBoost: 3,
      merchMultiplier: 1.04,
      concessionMultiplier: 1.04,
      awarenessBump: 2,
      sentimentBump: 4,
      reputationBump: 3,
      mediaBump: 2,
    },
    maxUsesPerSeason: 2,
    cooldownDays: 28,
  },
  {
    id: "community_appreciation",
    name: "Community Appreciation",
    description: "A night dedicated to thanking the local community.",
    category: "community_pr",
    objective: "community",
    targetAudience: "community",
    cost: 12_000,
    leadTimeDays: 5,
    effects: {
      demandBoost: 2,
      merchMultiplier: 1.02,
      concessionMultiplier: 1.02,
      awarenessBump: 1,
      sentimentBump: 3,
      reputationBump: 2,
      mediaBump: 1,
    },
    maxUsesPerSeason: 3,
    cooldownDays: 21,
  },
] as const;

const BY_ID: Record<string, GameDayPromotionDefinition> = Object.fromEntries(
  GAME_DAY_PROMOTION_CATALOG.map((d) => [d.id, d]),
);

export function getGameDayPromotionDefinition(
  promotionId: string,
): GameDayPromotionDefinition | undefined {
  return BY_ID[promotionId];
}

export function listGameDayPromotionDefinitions(): readonly GameDayPromotionDefinition[] {
  return GAME_DAY_PROMOTION_CATALOG;
}
