import type { ReactElement } from "react";
import type { TeamLogoId } from "@/data/team-branding/logo-catalog";
import type { TeamLogoProps } from "./LogoFrame";
import {
  BearLogo,
  BisonLogo,
  BullLogo,
  EagleLogo,
  FalconLogo,
  FoxLogo,
  LionLogo,
  OwlLogo,
  PantherLogo,
  RamLogo,
  SharkLogo,
  SnakeLogo,
  StagLogo,
  WolfLogo,
} from "./mascot-logos";
import {
  BasketballClawLogo,
  BasketballCrownLogo,
  BasketballFlameLogo,
  BasketballHoopLogo,
  BasketballLightningLogo,
  BasketballLogo,
  BasketballSpeedLogo,
  BasketballStarLogo,
  BasketballWingsLogo,
} from "./sports-logos";
import {
  ClawMarksLogo,
  FangLogo,
  FlameLogo,
  HornsLogo,
  LightningLogo,
  MeteorLogo,
  MountainPeakLogo,
  StarburstLogo,
  TornadoLogo,
  WaveSurgeLogo,
} from "./power-logos";
import {
  CrestLogo,
  CrownLogo,
  DiamondLogo,
  LaurelLogo,
  MonogramLogo,
  PennantLogo,
  RoundelLogo,
  ShieldLogo,
  StarLogo,
} from "./classic-logos";
import {
  BridgeLogo,
  CompassLogo,
  GlobeLogo,
  LighthouseLogo,
  MountainLogo,
  PalmTreeLogo,
  PineTreeLogo,
  SkylineLogo,
  SunLogo,
  WaveLogo,
} from "./regional-logos";

export const LOGO_COMPONENTS = {
  // Mascots
  wolf: WolfLogo,
  bear: BearLogo,
  eagle: EagleLogo,
  lion: LionLogo,
  panther: PantherLogo,
  falcon: FalconLogo,
  bull: BullLogo,
  ram: RamLogo,
  stag: StagLogo,
  shark: SharkLogo,
  fox: FoxLogo,
  bison: BisonLogo,
  snake: SnakeLogo,
  owl: OwlLogo,
  // Sports
  basketball: BasketballLogo,
  "basketball-hoop": BasketballHoopLogo,
  "basketball-speed": BasketballSpeedLogo,
  "basketball-wings": BasketballWingsLogo,
  "basketball-flame": BasketballFlameLogo,
  "basketball-claw": BasketballClawLogo,
  "basketball-crown": BasketballCrownLogo,
  "basketball-lightning": BasketballLightningLogo,
  "basketball-star": BasketballStarLogo,
  // Power
  lightning: LightningLogo,
  flame: FlameLogo,
  "claw-marks": ClawMarksLogo,
  fang: FangLogo,
  horns: HornsLogo,
  meteor: MeteorLogo,
  tornado: TornadoLogo,
  "mountain-peak": MountainPeakLogo,
  "wave-surge": WaveSurgeLogo,
  starburst: StarburstLogo,
  // Classic
  shield: ShieldLogo,
  crown: CrownLogo,
  star: StarLogo,
  monogram: MonogramLogo,
  crest: CrestLogo,
  laurel: LaurelLogo,
  pennant: PennantLogo,
  roundel: RoundelLogo,
  diamond: DiamondLogo,
  // Regional
  mountain: MountainLogo,
  wave: WaveLogo,
  skyline: SkylineLogo,
  bridge: BridgeLogo,
  "palm-tree": PalmTreeLogo,
  "pine-tree": PineTreeLogo,
  lighthouse: LighthouseLogo,
  compass: CompassLogo,
  sun: SunLogo,
  globe: GlobeLogo,
} satisfies Record<TeamLogoId, (props: TeamLogoProps) => ReactElement>;

export { ShieldLogo };
